
version: '1.0'
services:
  api:
    container_name: backend
    build: ./BackJWT
    command: npm run start
    volumes:
      - ./BackJWT:/BackJWT
    ports:
      - '8000:8000'

  frontend:
    container_name: frontend
    build:
      context: ./vuetifyGP
      dockerfile: Dockerfile
    volumes:
      - ./vuetifyGP:/app
      - /app/node_modules    
    ports:
      - '3000:3000'


